import { test, expect } from "@playwright/test";

test.describe("Blog", () => {
	test.describe("Blog Listing Page", () => {
		test.beforeEach(async ({ page }) => {
			await page.goto("/blog/");
		});

		test("should display page title", async ({ page }) => {
			const heading = page.locator("h1");
			await expect(heading).toHaveText("Posts");
		});

		test("should display blog posts as tiles", async ({ page }) => {
			const tiles = page.locator("pob-tile");
			await expect(tiles.first()).toBeVisible();
		});

		test("should display post titles", async ({ page }) => {
			const postTitle = page.locator("pob-tile strong");
			await expect(postTitle.first()).toBeVisible();
		});

		test("should display post dates", async ({ page }) => {
			const postDate = page.locator("pob-tile time");
			await expect(postDate.first()).toBeVisible();
		});

		test("should have links to individual posts", async ({ page }) => {
			const firstTile = page.locator("pob-tile").first();
			const href = await firstTile.getAttribute("href");
			expect(href).toBeTruthy();
			expect(href).toContain("/blog/");
		});

		test("should display tag filters when posts have tags", async ({ page }) => {
			const tagFilters = page.locator(".tag-filters");
			// Tags may or may not be present depending on posts
			const count = await tagFilters.count();
			if (count > 0) {
				await expect(tagFilters).toBeVisible();
				const tagLinks = page.locator(".tags-list a.tag");
				await expect(tagLinks.first()).toBeVisible();
			}
		});
	});

	test.describe("Individual Blog Post", () => {
		test.beforeEach(async ({ page }) => {
			// Navigate to the Hello World post
			await page.goto("/blog/2024/07/hello-world/");
		});

		test("should display post title", async ({ page }) => {
			const heading = page.locator("h1");
			await expect(heading).toHaveText("Hello, World!");
		});

		test("should display post date", async ({ page }) => {
			// Date is rendered as <time> element directly after h1
			const dateElement = page.locator("article time").first();
			await expect(dateElement).toBeVisible();
		});

		test("should display post content", async ({ page }) => {
			const content = page.locator("article");
			await expect(content).toBeVisible();
			// Check for some expected content
			await expect(content).toContainText("Eleventy");
		});

		test("should display tags", async ({ page }) => {
			// Tags are in .tags-list container
			const tags = page.locator("article .tags-list .tag");
			await expect(tags.first()).toBeVisible();
			await expect(tags.first()).toHaveText("meta");
		});

		test("should generate table of contents for posts with headings", async ({ page }) => {
			// The TOC is in nav#toc which is slotted into the sidebar
			// The ol is generated by the table-of-contents plugin
			const toc = page.locator("nav#toc");
			await expect(toc).toBeVisible();

			// Should have links to headings
			const tocLinks = toc.locator("ol a");
			await expect(tocLinks.first()).toBeVisible();
		});

		test("should have heading IDs for TOC navigation", async ({ page }) => {
			// Headings get IDs generated from their text
			const heading = page.locator("article h2").first();
			await expect(heading).toBeVisible();
			const id = await heading.getAttribute("id");
			expect(id).toBeTruthy();
		});

		test("should render pob-note components", async ({ page }) => {
			const note = page.locator("pob-note");
			await expect(note).toBeVisible();
		});
	});

	test.describe("Blog Post Navigation", () => {
		test.use({ viewport: { width: 1280, height: 720 } });

		test("should navigate from listing to post", async ({ page }) => {
			await page.goto("/blog/");

			const firstTile = page.locator("pob-tile").first();
			await firstTile.click();

			// Should be on a blog post page
			await expect(page.locator("article")).toBeVisible();
			await expect(page.locator("h1")).toBeVisible();
		});

		test("should have link back to blog from post", async ({ page }) => {
			await page.goto("/blog/2024/07/hello-world/");

			// Navigation is inside shadow DOM of pob-app
			// Use shadow DOM piercing selector to find the Blog nav link
			const blogLink = page.locator("pob-app >> .top-nav >> text=Blog");
			await expect(blogLink).toBeVisible();
		});
	});

	test.describe("Syntax Highlighting", () => {
		test("should render syntax-highlighted code blocks", async ({ page }) => {
			// Navigate to a post that might have code blocks
			// For now, we'll just check the component exists if present
			await page.goto("/blog/2024/07/hello-world/");

			// This post may not have code blocks, so we just verify
			// the page loads correctly even without them
			await expect(page.locator("h1")).toBeVisible();
		});
	});
});
